"""
Generates .pyi stub files so IDEs (PyCharm, VS Code, mypy, etc.) recognize
methods added dynamically by installed plugins.
"""

import importlib
import inspect
from pathlib import Path
from typing import Callable, Dict, List

from cozy_kit.plugins.core.registry import fetch_plugin, list_plugins
from cozy_kit.plugins.core.installer import _resolve_target
from cozy_kit._internal.helpers.import_helpers import load_module_from_path


def _annotation_to_str(annotation) -> str:
    if annotation is inspect.Parameter.empty:
        return "Any"
    if annotation is type(None):
        return "None"
    if hasattr(annotation, "__name__"):
        return annotation.__name__
    raw = str(annotation)
    return raw.replace("typing.", "")


def _fmt_param(name: str, param: inspect.Parameter) -> str:
    if name == "self":
        return "self"
    if name == "cls":
        return "cls"

    ann = _annotation_to_str(param.annotation)
    has_default = param.default is not inspect.Parameter.empty
    default_suffix = " = ..." if has_default else ""

    if param.kind == inspect.Parameter.VAR_POSITIONAL:
        return f"*{name}: {ann}"
    if param.kind == inspect.Parameter.VAR_KEYWORD:
        return f"**{name}: {ann}"

    return f"{name}: {ann}{default_suffix}"


def _fmt_signature(fn: Callable, is_init: bool = False) -> str:
    """Return a stub-safe '(self, arg: Type = ...) -> ReturnType' string."""
    try:
        sig = inspect.signature(fn)
    except (ValueError, TypeError):
        return "(self, *args: Any, **kwargs: Any) -> Any"

    params = [_fmt_param(n, p) for n, p in sig.parameters.items()]
    if is_init:
        ret = "None"
    else:
        ret = _annotation_to_str(sig.return_annotation)
    return f"({', '.join(params)}) -> {ret}"


def _collect_class_lines(cls: type, skip_names: set) -> List[str]:
    lines: List[str] = []
    seen: set = set()

    for klass in reversed(cls.__mro__):
        if klass is object:
            continue
        for name, val in klass.__dict__.items():
            if name in seen or name in skip_names:
                continue
            if name.startswith("_") and name not in ("__init__",):
                continue
            seen.add(name)

            if isinstance(val, property):
                prop_ret = _annotation_to_str(
                    getattr(val.fget, "__annotations__", {}).get(
                        "return", inspect.Parameter.empty
                    )
                )
                lines.append(f"    @property")
                lines.append(f"    def {name}(self) -> {prop_ret}: ...")

            elif isinstance(val, staticmethod):
                sig = _fmt_signature(val.__func__)
                lines.append(f"    @staticmethod")
                lines.append(f"    def {name}{sig}: ...")

            elif isinstance(val, classmethod):
                sig = _fmt_signature(val.__func__)
                lines.append(f"    @classmethod")
                lines.append(f"    def {name}{sig}: ...")

            elif callable(val):
                is_init = name == "__init__"
                sig = _fmt_signature(val, is_init=is_init)
                lines.append(f"    def {name}{sig}: ...")

    return lines


def generate_stubs(*plugin_names: str) -> Dict[str, str]:
    """
    Generate (or update) .pyi stub files for one or more installed plugins.

    Args:
        *plugin_names: Names of registered plugins to include in the stubs.
                       Pass no arguments to generate stubs for every registered plugin.

    Returns:
        Dict mapping each stub file path to the class name it covers.
    """
    if not plugin_names:
        plugin_names = tuple(list_plugins().keys())

    per_target: Dict[str, List] = {}

    for name in plugin_names:
        plugin_data = fetch_plugin(name)
        target_name = plugin_data.get("target")
        if not target_name:
            continue

        engine_module = load_module_from_path(
            plugin_data["engine_path"], f"_cozy_stub_engine_{name}"
        )
        methods: Dict[str, Callable] = {}
        for method_name in plugin_data["methods"]:
            fn = getattr(engine_module, method_name, None)
            if fn is not None:
                methods[method_name] = fn

        per_target.setdefault(target_name, []).append((name, methods))

    result: Dict[str, str] = {}

    for target_name, plugin_list in per_target.items():
        target_cls = _resolve_target(target_name)

        target_module = importlib.import_module(target_cls.__module__)
        module_file = Path(target_module.__file__)
        stub_path = module_file.with_suffix(".pyi")

        lines: List[str] = [
            "# Auto-generated by cozy-kit plugin system.",
            "# Run generate_stubs() again after installing additional plugins.",
            "from typing import Any, Optional",
            "",
            f"class {target_name}:",
        ]

        all_plugin_methods = {m for _, methods in plugin_list for m in methods}

        class_lines = _collect_class_lines(target_cls, skip_names=all_plugin_methods)
        if not class_lines:
            lines.append("    ...")
        else:
            lines.extend(class_lines)

        for plugin_name, methods in plugin_list:
            plugin_data = fetch_plugin(plugin_name)
            version = plugin_data.get("version", "")
            lines.append(f"")
            lines.append(f"    # Plugin: {plugin_name} v{version}")
            for method_name, fn in methods.items():
                sig = _fmt_signature(fn)
                lines.append(f"    def {method_name}{sig}: ...")

        stub_content = "\n".join(lines) + "\n"
        stub_path.write_text(stub_content, encoding="utf-8")
        result[str(stub_path)] = target_name

    return result
